config/routes.rb
Rails.application.routes.draw do

  get 'show_users', to: 'admin#show_users'
  get 'show_orders', to: 'admin#show_orders'
  post 'admin/destroy'
  post 'admin/update_order'

  get 'search', to: 'pages#search'

  get 'orders', to: 'orders#show'
  post 'orders/add'

  get 'checkout', to: 'checkout#show'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  root 'pages#home'
  resources :products
  devise_for :users

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  def show
  end

  def add
    @product = Product.find(params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)

    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart }),
                              turbo_stream.replace(@product,),
                              turbo_stream.replace('cart_count', partial: 'cart/cart_count', locals: { cart: @cart}),
                              turbo_stream.replace('grand_total', partial: 'cart/grand_total', locals: { cart: @cart}),
                              turbo_stream.replace('checkout', partial: 'checkout/checkout', locals: { cart: @cart}),]
                                                               # here @product because in _products.html.erb it already has the dom id for the product so it can figure it out on its own
      end                                                      # main reason for replacing is because we are updating our product quantities
    end

  end

  def remove
    Orderable.find_by(id: params[:id]).destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart }),
                              turbo_stream.replace('cart_count', partial: 'cart/cart_count', locals: { cart: @cart}),
                              turbo_stream.replace('grand_total', partial: 'cart/grand_total', locals: { cart: @cart}),
                              turbo_stream.replace('checkout', partial: 'checkout/checkout', locals: { cart: @cart}),]
      end
    end
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<% if current_user && current_user.role == 0 %>

    <%= turbo_frame_tag "cart" do %>
    <div class="p-5">
        <h1 style="text-align: center; font-weight: bold;">Your Cart</h1>
        <% if @cart.orderables.count > 0 %>
            <%= render "cart/orderables" %>
        <% else %>
            <div class="d-flex justify-content-center">
                <p style="font-weight: bold; font-size: 20px">Cart is empty</p>   
            </div> 
        <% end %>
    </div>
    <% end %>

<% end %>

app/views/cart/_cart_count.html.erb
<%= turbo_frame_tag "cart_count" do %>
    <i class="fa fa-shopping-cart fa-lg"> (<%= @cart.orderables.count %>)</i>
<% end %>

app/views/cart/_grand_total.html.erb
<%= turbo_frame_tag "grand_total" do %>
    <div class="pb-5">
        <h3 style="font-weight: bold; text-align: center;">Grand Total: Rs. <span style="color: #194270"><%= @cart.total %></span>/-</h3>
    </div>
<% end %>

app/views/cart/_orderables.html.erb
<style>
    .input-field{
        width: 50px;
    }

    .btn-style{
        width: 130px;
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
    }

    .btn-style:hover{
        color: white;
        background-color: #0d233c;
        transition: all 0.3s ease;
    }

</style>


<div class="d-flex flex-wrap m-5 justify-content-center align-items-center" style="gap: 100px;"> 
<% @cart.orderables.each do |orderable| %>
    <% product = orderable.product %>
    <div id="<%= "cart-#{product.id}" %>">
        
        <div style="width: 300px; height: 55vh; border-width: 2px; border-radius: 15px" class="border border-primary d-flex flex-column align-items-center shadow-lg">
            <div class="d-flex justify-content-center align-items-center" style="height: 60%">
                <%= image_tag(product.image_as_thumbnail) %>
            </div>

            <div class="d-flex flex-column p-2 justify-content-center align-items-center" style="width: 100%;">

                <p class="font-weight-bold"><%= product.name %></p>

                <%= form_with(url: cart_add_path) do |f| %>

                    <%= f.hidden_field :id, value: product.id %>
                    <div style="width: 100%;" class="d-flex align-items-center justify-content-between">
                        <p>Quantity: </p> 
                        <p> <%= f.number_field :quantity, value: orderable.quantity, min: 0, class: "input-field" %></p>
                    </div>

                    <div>
                        <%= f.submit "Update Cart", class: "btn btn-style" %>
                    </div>

                <% end %>

                <%= form_with(url: cart_remove_path) do |f| %>
                    <%= f.hidden_field :id, value: orderable.id %>
                    <div class="mt-3">
                        <%= f.submit "Remove", class: "btn btn-danger btn-mini" %>
                    </div>
                <% end %>

                <div class="mt-3">
                    <h6 style="font-weight: bold;">Total: <%= orderable.total %></h6>
                </div>
            </div>
        </div>
    </div>

<% end %>
</div>

app/views/cart/show.html.erb
<style>
    .btn-style-3{
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
        width: 180px;
    }

    .btn-style-2{
        background-color: #24bdd1;
        color: white;
        transition: all 0.3s ease;
        width: 180px;
    }

    .btn-style-3:hover, .btn-style-2:hover{
        color: white;
        transition: all 0.3s ease;
        transform: scale(1.1)
    }
</style>


<% if current_user && current_user.role == 0 %>

    <%= render partial: 'cart/cart' %>

    <%= render partial: 'cart/grand_total' %>

    <div class="d-flex justify-content-center align-items-center mb-5" style="gap: 30px">
        <%= link_to "Continue Shopping", products_path, class: "btn btn-style-3" %>
        <%= render partial: "checkout/checkout" %>
    </div>

<% end %>