config/routes.rb
Rails.application.routes.draw do

  get 'show_users', to: 'admin#show_users'
  get 'show_orders', to: 'admin#show_orders'
  post 'admin/destroy'
  post 'admin/update_order'

  get 'search', to: 'pages#search'

  get 'orders', to: 'orders#show'
  post 'orders/add'

  get 'checkout', to: 'checkout#show'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  root 'pages#home'
  resources :products
  devise_for :users

end

app/views/admin/show_orders.html.erb
<main class="p-5">
    <h1 style="font-weight: bold; text-align: center;">Orders</h1>

    <div class="mt-5 d-flex justify-content-center align-items-center flex-wrap" style="gap: 100px">
        <% @orders.each do |order| %>
            <div class="p-3 shadow-lg" style="border: 1px solid #194270; border-radius: 10px">
                <p><strong>Username: </strong><%= order.user.name %></p>
                <p><strong>Email: </strong><%= order.user.email %></p>
                <p><strong>Products: </strong><%= order.total_products %></p>
                <p><strong>Price: </strong>Rs. <%= order.total_price %></p>
                <p><strong>Placed On: </strong><%= order.created_at %></p>
                <p><strong>Status: </strong><%= (order.status == 0) ? "Pending" : "Completed" %></p>
                <%= form_with(url: admin_update_order_path) do |f| %>
                    <%= f.hidden_field :id, value: order.id %>
                    <%= f.select :status, ["Choose...", "Pending", "Completed"], {}, {class: "custom-select d-block w-100"} %>
                    <div class="mt-3 d-flex justify-content-center">
                        <%= f.submit "Update Order", class: "btn btn-success btn-mini" %>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>

</main>

app/views/admin/show_users.html.erb
<main class="p-5">
    <h1 style="font-weight: bold; text-align: center;">Users</h1>

    <div class="mt-5 d-flex justify-content-center align-items-center flex-wrap" style="gap: 100px">
    
        <% @users.each do |user| %>
            <div class="d-flex flex-column justify-content-center p-3 shadow-lg" style="border: 1px solid #194270; border-radius: 10px">
                <p><strong>Name: </strong> <%= user.name %></p>
                <p><strong>Email: </strong> <%= user.email %></p>
                
                <% if user == current_user %>
                    <div class="d-flex justify-content-center">
                        <p class="text-white m-0 px-3 py-2 mt-3" style="background-color: #24bdd1; border-radius: 5px">Currenlty Logged In</p>
                    </div>
                <% else %>
                    <div class="d-flex justify-content-center">
                        <%= form_with(url: admin_destroy_path) do |f| %>
                            <%= f.hidden_field :id, value: user.id %>
                            <div class="mt-3">
                                <%= f.submit "Delete User", class: "btn btn-danger btn-mini" %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            </div>
        <% end %>
    
    </div>

</main>