config/routes.rb
Rails.application.routes.draw do

  get 'show_users', to: 'admin#show_users'
  get 'show_orders', to: 'admin#show_orders'
  post 'admin/destroy'
  post 'admin/update_order'

  get 'search', to: 'pages#search'

  get 'orders', to: 'orders#show'
  post 'orders/add'

  get 'checkout', to: 'checkout#show'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  root 'pages#home'
  resources :products
  devise_for :users

end

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
    <div class="bg-success text-white d-flex justify-content-center align-items-center" style="width: 100%; height: 40px;">
        <%= msg %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="p-5 d-flex flex-wrap justify-content-between" style="background-color: #dddddd">
    <div class="d-flex flex-column align-items-start mb-10 w-25">
        <%= link_to "", root_path, class: "home-icon" %>
        <p class="mt-5">We're the best in our field, and it's all thanks to the incredible relationships we've formed with our clients. Get in touch with us when you're ready to learn more: we can't wait to meet you!</p>
    </div>

    <div class="d-flex flex-column align-items-start mb-10">
        <h4 class="mb-5 font-weight-bold">Contact</h4>
        <p><strong>Address: </strong> ARFA Software Technology Park, Lahore</p>
        <p><strong>Phone: </strong> (042) 31234567 </p>
        <p><strong>Hours: </strong> 10:00AM - 6:00PM, Monday - Saturday</p>

        <div id="follow" class="mt-5">
            <h4 class="font-weight-bold">Follow Us</h4>
            <div>
                <i class="fa fa-facebook mr-2"></i>
                <i class="fa fa-twitter mr-2"></i>
                <i class="fa fa-instagram mr-2"></i>
                <i class="fa fa-youtube-play"></i>
            </div>
        </div>
    </div>

    <div class="d-flex flex-column align-items-start mb-10">
        <h4 class="mb-5 font-weight-bold">Payment Methods</h4>
        <p>Secured Payment Gateways</p>
        <%= image_tag "pay.png" %>
    </div>

    <div class="d-flex justify-content-center align-items-center w-100">
        <p class="mt-5" style="color: #088178">&copy; 2022, Sab Lay Jao. All Rights Reserved</p>
    </div>

</footer>

app/views/shared/_nav.html.erb
<nav class="py-4 navbar navbar-expand-lg navbar-dark" style="position: sticky; top: 0px; z-index: 1000; background-color: #194270;">
  <%= link_to image_tag('logo.png'), root_path %>
  <%= link_to "abLayJao", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Products", products_path, class: "nav-link" %>
      </li>
      <li>
        <% if current_user && current_user.role == 1%>
          <%= link_to "Add Product", new_product_path, class: "nav-link" %>
        <% end %>
      </li>
      <li>
        <% if current_user && current_user.role == 0%>
          <%= link_to "My Orders", orders_path, class: "nav-link" %>
        <% elsif current_user && current_user.role == 1 %>
          <%= link_to "Orders", show_orders_path, class: "nav-link" %>
        <% end %>
      </li>
      <li>
        <% if current_user && current_user.role == 1%>
          <%= link_to "Users", show_users_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>

    <!-- Search bar -->
    <form class="form-inline my-2 my-lg-0" method="GET" action="/search">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <!-- Search bar end -->

    <ul class="navbar-nav ml-3">
        <li class="nav-item">
            <% if current_user %>
                <%= link_to ("<i class='fa fa-user-circle-o fa-lg'></i>").html_safe, edit_user_registration_path, class: "nav-link" %>
            <% else %>
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <% end %>
        </li>
        <li class="nav-item">
            <% if current_user %>
                <%= link_to "Logout", destroy_user_session_path, 'data-turbo-method': :delete, class: "nav-link" %>
            <% else %>
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            <% end %>
        </li>
        <li class="nav-item">
          <% if current_user && current_user.role == 0 %>
            <%= link_to cart_path do %>
              <div class="nav-link">
                <%= render partial: 'cart/cart_count' %>
              </div>
            <% end %>
          <% end %>
        </li>
    </ul>

  </div>
</nav>