config/routes.rb
Rails.application.routes.draw do

  get 'show_users', to: 'admin#show_users'
  get 'show_orders', to: 'admin#show_orders'
  post 'admin/destroy'
  post 'admin/update_order'

  get 'search', to: 'pages#search'

  get 'orders', to: 'orders#show'
  post 'orders/add'

  get 'checkout', to: 'checkout#show'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  root 'pages#home'
  resources :products
  devise_for :users

end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    has_many :orderables
    has_many :carts, through: :orderables

    validates :name, :description, :category, :image, :presence => true
    validates_numericality_of :price, :only_integer => true, :greater_than => 0

    def image_as_thumbnail
        return unless image.content_type.in? (%w[image/jpeg image/png image/jpg])
        image.variant(resize_to_limit: [200, 200]).processed
    end

    def cover_image
        image.variant(resize_to_limit: [550, 550]).processed
    end

    def feature_image
        image.variant(resize_to_limit: [100, 100]).processed
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @users = User.all

    @users.each do |user|
      if user.role == 0
        user.cart.orderables.each do |orderable|
          @od = Orderable.where(id: orderable.id, product_id: @product.id)
          @od.destroy_all if !@od.nil?
        end
      end 
    end

    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<style>
    .btn-style{
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
        width: 180px
    }

    .btn-style-2{
        background-color: #24bdd1;
        color: white;
        transition: all 0.3s ease;
    }

    .btn-style:hover, .btn-style-2:hover{
        color: white;
        transition: all 0.3s ease;
        transform: scale(1.1)
    }
</style>

<div>

  <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-flex flex-column justify-content-center align-items-center">
      <div class="shadow-lg p-3 mb-5 bg-white rounded">
        <div class="form-outline mb-4">
          <div>
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-outline mb-4">
          <div>
            <%= form.label :description %>
            <%= form.text_field :description, class: "form-control" %>
          </div>
        </div>


        <div class="form-outline mb-4">
          <div>
            <%= form.label :price %>
            <%= form.number_field :price, class: "form-control" %>
          </div>
        </div>


        <div class="form-outline mb-4">
          <div>
            <%= form.label :category %>
            <%= form.text_field :category, class: "form-control" %>
          </div>
        </div>


        <div class="form-outline mb-4">
          <div>
            <%= form.label :image %>
            <%= form.file_field :image, style: "display: block" %>
          </div>
        </div>

        <div class="actions d-flex justify-content-center">
          <%= form.submit %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/products/_product.html.erb
<style>
    .btn-style{
        width: 130px;
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
    }

    .btn-style:hover{
        color: white;
        transition: all 0.3s ease;
        transform: scale(1.1)
    }

    .input-feild{
      width: 50px;
    }
</style>

<div id="<%= dom_id product %>">

  <div class="d-flex p-5" style="gap:100px;">
    <div id="image-container" style="width: 40%; height: 600px;" class="d-flex justify-content-center align-items-start">
      <% if product.image.content_type.in? (%w[image/jpeg image/png image/jpg]) %>
        <%= link_to image_tag(product.cover_image), product.image if product.image.attached? %>
      <% end %>
    </div> 

    <div class="d-flex flex-column align-items-start justify-content-start" style="width: 40%">
      <h3 style="font-size: 50px; color: #194270"><%= product.name %></h3>

      <div class="my-4">
        <h3 style="font-weight: bold; font-size: 30px;">Description</h3>
        <p><%= product.description %></p>
      </div>

      <div class="mb-4">
        <h3 style="font-weight: bold; font-size: 30px;">Category: <span style="color: #194270"><%= product.category %></span></h3>
      </div>

      <div class="mb-4 d-flex align-items-center justify-content-center">
        <h3 style="font-weight: bold; font-size: 30px;">Price: Rs. <span style="color: #194270"><%= product.price %></span>/-</h3>
      </div>

      <% if current_user && current_user.role == 0 %>
        <div class="d-flex flex-column justify-content-center align-items-start" style="gap: 50px">
          <%= form_with(url: cart_add_path) do |f| %>
            <%= f.hidden_field :id, value: product.id %>
            <div>
              <h3 style="font-weight: bold; font-size: 25px;">Quantity: <%= f.number_field :quantity, value: 0, min: 1, class: "input-feild" %></h3>
            </div>
            <div class="mt-5">
              <%= f.submit "Add to Cart", class: "btn btn-style" %>
            </div>
          <% end %>
      <% elsif current_user.nil? %>
        <div class="d-flex flex-column justify-content-center align-items-start" style="gap: 50px">
            <div>
              <h3 style="font-weight: bold; font-size: 25px;">Quantity: <input type="number" class="col-md-2" name="input" id="input" value="0" min="1"></h3>
            </div>
            <div>
              <%= link_to "Add to Cart", new_user_session_path, class: "btn btn-style" %>
            </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/products/edit.html.erb
<style>
    .btn-style{
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
    }

    .btn-style:hover{
        color: white;
        transition: all 0.3s ease;
        transform: scale(1.1)
    }
</style>

<main class="p-5">
  <h1 style="font-weight: bold; text-align: center" class="pb-5">Edit Product</h1>

  <%= render "form", product: @product %>

  <br>

  <div>
    <%= link_to "Back to products", products_path, class: "btn btn-style mr-5" %>
    <%= link_to "Show this product", @product, class: "btn btn-style" %>
  </div>
</main>

app/views/products/index.html.erb
<style>
    .btn-style{
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
        width: 180px
    }

    .btn-style-2{
        background-color: #24bdd1;
        color: white;
        transition: all 0.3s ease;
    }

    .btn-style:hover, .btn-style-2:hover{
        color: white;
        transition: all 0.3s ease;
        transform: scale(1.1)
    }
</style>

<main class="p-5">
  <h1 style="font-weight: bold; text-align:center" class="pb-2">Products</h1>

  <div id="products" class="d-flex flex-wrap justify-content-center" style="gap: 50px">
    <% if @products.count > 0 %>
      <% @products.each do |product| %>

        <div style="width: 300px; height: 45vh; border-width: 2px; border-radius: 15px" class="my-5 border border-primary d-flex flex-column align-items-center shadow-lg">
          <div class="d-flex justify-content-center align-items-center" style="height: 60%">
            <%= image_tag(product.image_as_thumbnail) %>
          </div>
          <div class="d-flex flex-column p-2 justify-content-center align-items-center">
          <p><%= product.name %></p>
          <h3 style="font-weight: bold; color: #194270">Rs. <%= product.price %></h3>
          </div>
          <%= link_to "Show Product", product, class: "btn btn-style" %>
        </div>

      <% end %>
    <% else %>
      <div class="m-5">
        <p style="font-size: 30px">No Products Found</p>
      </div>
    <% end %>
  </div>

</main>

app/views/products/new.html.erb
<style>
    .btn-style{
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
    }

    .btn-style:hover{
        color: white;
        transition: all 0.3s ease;
        transform: scale(1.1)
    }
</style>

<main class="p-5">
  <h1 style="font-weight: bold; text-align: center" class="pb-5">Add Product</h1>

  <%= render "form", product: @product %>

  <br>

  <div>
    <%= link_to "Back to Products", products_path, class: "btn btn-style" %>
  </div>
</main>

app/views/products/show.html.erb
<style>
    .btn-style{
        background-color: #194270;
        color: white;
        transition: all 0.3s ease;
        width: 180px
    }

    .btn-style:hover, .btn-edit:hover, .btn-delete:hover{
        color: white;
        transition: all 0.3s ease;
        transform: scale(1.1)
    }

    .btn-edit{
      width: 100px;
      color: white;
      background-color: #ffd700;
      transition: all 0.3s ease;
    }

    .btn-delete{
      width: 100px;
      color: white;
      background-color: #c70039;
      transition: all 0.3s ease;
    }

    i{
      size: 100px
    }
</style>

<main class="py-5">
  <%= render @product %>

  <% if current_user && current_user.role == 1 %>
    <div class="p-3 d-flex justify-content-end align-items-center" style="width: 100%; gap: 20px">
      <%= link_to ("<i class='fa fa-edit fa-3x'></i>").html_safe, edit_product_path(@product), class: "btn btn-edit" %>
      <%= button_to ("<i class='fa fa-trash fa-3x'></i>").html_safe, @product, method: :delete, class: "btn btn-delete" %>
    </div>
  <% end %>
</main>